//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_THUEXEEntities : DbContext
    {
        public QL_THUEXEEntities()
            : base("name=QL_THUEXEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoaiNguoiDung> LoaiNguoiDungs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblDongXe> tblDongXes { get; set; }
        public virtual DbSet<tblGiaoDich> tblGiaoDiches { get; set; }
        public virtual DbSet<tblHopDong> tblHopDongs { get; set; }
        public virtual DbSet<tblHuy> tblHuys { get; set; }
        public virtual DbSet<tblLoaiDichVu> tblLoaiDichVus { get; set; }
        public virtual DbSet<tblMenu> tblMenus { get; set; }
        public virtual DbSet<tblMucPhi> tblMucPhis { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblXe> tblXes { get; set; }
        public virtual DbSet<tblDoiMatKhau> tblDoiMatKhaus { get; set; }
    }
}
