//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlogComment
    {
        public int CmtId { get; set; }
        public Nullable<int> BlogId { get; set; }
        public string Name { get; set; }
        public string Cmt { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
    
        public virtual tblBlog tblBlog { get; set; }
    }
}
