//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBlog
    {
        public int BlogId { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public string SubTitle { get; set; }
        public string Text1 { get; set; }
        public string Image1 { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
