//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoiMatKhau
    {
        public int id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string password { get; set; }
        public string rePassword { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
