//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiaoDich
    {
        public string MaGD { get; set; }
        public Nullable<int> MaHopDong { get; set; }
        public string MaPayment { get; set; }
        public string TrangThai { get; set; }
    
        public virtual tblHopDong tblHopDong { get; set; }
        public virtual tblPayment tblPayment { get; set; }
    }
}
