//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHuy
    {
        public int MaHuy { get; set; }
        public string MaHopDong { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<System.DateTime> ThoiGianHuy { get; set; }
    
        public virtual tblHopDong tblHopDong { get; set; }
    }
}
