//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHopDong()
        {
            this.tblGiaoDiches = new HashSet<tblGiaoDich>();
            this.tblHuys = new HashSet<tblHuy>();
        }
    
        public int MaHopDong { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<System.DateTime> NgayNhanXe { get; set; }
        public Nullable<System.DateTime> NgayTraXe { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TienDatCoc { get; set; }
        public Nullable<int> User_id { get; set; }
        public string TenDayDu { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string NoiThue { get; set; }
        public string NoiTra { get; set; }
        public Nullable<int> SoNgayThue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGiaoDich> tblGiaoDiches { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblXe tblXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHuy> tblHuys { get; set; }
    }
}
