//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public int MenuId { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Positions { get; set; }
    }
}
