//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblXe()
        {
            this.tblHopDongs = new HashSet<tblHopDong>();
        }
    
        public int MaXe { get; set; }
        public Nullable<int> User_id { get; set; }
        public Nullable<int> MaMP { get; set; }
        public Nullable<int> MaDongXe { get; set; }
        public Nullable<int> MaLoaiDV { get; set; }
        public Nullable<System.DateTime> NgayDK { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> LuotThue { get; set; }
        public string Image { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Title { get; set; }
        public string Sub { get; set; }
        public string Description { get; set; }
    
        public virtual tblDongXe tblDongXe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHopDong> tblHopDongs { get; set; }
        public virtual tblLoaiDichVu tblLoaiDichVu { get; set; }
        public virtual tblMucPhi tblMucPhi { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
